/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iAuctionHouseInterfaceSol from "./IAuctionHouseInterface.sol";
export type { iAuctionHouseInterfaceSol };
import type * as iAuctonSol from "./IAucton.sol";
export type { iAuctonSol };
export type { IAuction } from "./IAuction";
export type { IAuctionHouseService } from "./IAuctionHouseService";
