/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAuction } from "./IAuction";
export type { IAuctionHouseService } from "./IAuctionHouseService";
export type { IQueryService } from "./IQueryService";
