/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iAuctionHouseInterfaceSol from "./IAuctionHouseInterface.sol";
export * as iAuctonSol from "./IAucton.sol";
export { IAuction__factory } from "./IAuction__factory";
export { IAuctionHouseService__factory } from "./IAuctionHouseService__factory";
